[project]
name = "NanoTrade"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.nanotrade]
path = "contracts/nanotrade.clar"
depends_on = []

[contracts.nanotrade-ratings]
path = "contracts/nanotrade-ratings.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
